import type { Metadata, Viewport } from "next";
import { Newsreader, Hanken_Grotesk, Caveat } from "next/font/google";
import "./globals.css";

// Serif for everything you read: headings and body, like a letter.
const serif = Newsreader({
  subsets: ["latin"],
  axes: ["opsz"],
  style: ["normal", "italic"],
  variable: "--font-serif",
  display: "swap",
});

// Small sans for dates, stacks and buttons.
const sans = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

// Handwriting for the margin notes and sketch labels only.
const note = Caveat({
  subsets: ["latin"],
  variable: "--font-note",
  display: "swap",
});

// Matches the paper colour so mobile browser chrome blends into the page.
export const viewport: Viewport = {
  themeColor: "#FAF9F6",
  colorScheme: "light",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://rogerdemello.tech"),
  title: "Roger Richard Demello - Software Engineer, AI/ML",
  description: "Software engineer shipping machine learning and generative AI systems end to end - Python and TypeScript services over PostgreSQL, Docker delivery through CI/CD, 3 production applications for 200+ users at 99.5% uptime. RAG pipelines, multi-agent systems, FastAPI, LangChain, AWS.",
  keywords: [
    "Roger Demello",
    "Software Engineer",
    "Software Engineer AI/ML",
    "AI Engineer",
    "Machine Learning Engineer",
    "Generative AI",
    "LLM Applications",
    "AI Agents",
    "RAG Pipelines",
    "Multi-Agent Systems",
    "LangChain",
    "LangGraph",
    "MLOps",
    "Python",
    "TypeScript",
    "FastAPI",
    "AWS Cloud",
    "Portfolio"
  ],
  authors: [{ name: "Roger Richard Demello" }],
  creator: "Roger Richard Demello",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://rogerdemello.tech/",
    title: "Roger Richard Demello - Software Engineer, AI/ML",
    description: "Software engineer shipping machine learning and generative AI systems end to end. 3 production applications for 200+ users at 99.5% uptime. RAG pipelines, multi-agent systems, FastAPI, LangChain, AWS.",
    siteName: "Roger Demello Portfolio",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Roger Richard Demello - Software Engineer, AI/ML",
    description: "Software engineer shipping machine learning and generative AI systems end to end. 3 production applications for 200+ users at 99.5% uptime.",
    site: "@rogerr_289",
    creator: "@rogerr_289",
    // twitter:image is generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

// Structured data so search engines and recruiter tools read this page as a person, not a blob.
const personLd = {
  "@context": "https://schema.org",
  "@type": "Person",
  name: "Roger Richard Demello",
  alternateName: "Roger Demello",
  jobTitle: "Software Engineer, AI/ML",
  url: "https://rogerdemello.tech",
  address: { "@type": "PostalAddress", addressLocality: "Nagpur", addressCountry: "IN" },
  alumniOf: {
    "@type": "CollegeOrUniversity",
    name: "Shri Ramdeobaba College of Engineering and Management",
  },
  sameAs: ["https://github.com/rogerdemello", "https://linkedin.com/in/rogerdemello"],
  knowsAbout: ["Machine learning", "Generative AI", "Retrieval-augmented generation", "Multi-agent systems", "Python", "TypeScript", "FastAPI", "AWS"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${serif.variable} ${sans.variable} ${note.variable}`}
    >
      {/* Browser extensions (Grammarly et al.) inject attributes into <body>
          before hydration; suppress the resulting mismatch warning. Scoped to
          this element only - real mismatches inside the tree still surface. */}
      <body
        className="bg-paper font-serif text-ink antialiased"
        suppressHydrationWarning
      >
        <a
          href="#main-content"
          className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-[100] focus:rounded-md focus:bg-ink focus:px-5 focus:py-2.5 focus:font-sans focus:text-sm focus:font-semibold focus:text-paper"
        >
          Skip to content
        </a>
        {children}
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(personLd) }} />
      </body>
    </html>
  );
}
