import type { Metadata, Viewport } from "next";
import { Instrument_Serif, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Editorial display serif for headings - elegant, distinctive, not a default sans.
const serif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-display",
  display: "swap",
});

// Clean workhorse for body copy.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

// Monospace for labels, metadata, terminal UI, and code.
const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

// Dark instrument surface - keeps mobile browser chrome from flashing white.
export const viewport: Viewport = {
  themeColor: "#0B0D0F",
  colorScheme: "dark",
};

export const metadata: Metadata = {
  metadataBase: new URL("https://rogerdemello.tech"),
  title: "Roger Richard Demello - Software Engineer, AI/ML",
  description: "Software engineer shipping machine learning and generative AI systems end to end - Python and TypeScript services over PostgreSQL, Docker delivery through CI/CD, 3 production applications for 200+ users at 99.5% uptime. RAG pipelines, multi-agent systems, FastAPI, LangChain, AWS.",
  keywords: [
    "Roger Demello",
    "Software Engineer",
    "Software Engineer AI/ML",
    "AI Engineer",
    "Machine Learning Engineer",
    "Generative AI",
    "LLM Applications",
    "AI Agents",
    "RAG Pipelines",
    "Multi-Agent Systems",
    "LangChain",
    "LangGraph",
    "MLOps",
    "Python",
    "TypeScript",
    "FastAPI",
    "AWS Cloud",
    "Portfolio"
  ],
  authors: [{ name: "Roger Richard Demello" }],
  creator: "Roger Richard Demello",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://rogerdemello.tech/",
    title: "Roger Richard Demello - Software Engineer, AI/ML",
    description: "Software engineer shipping machine learning and generative AI systems end to end. 3 production applications for 200+ users at 99.5% uptime. RAG pipelines, multi-agent systems, FastAPI, LangChain, AWS.",
    siteName: "Roger Demello Portfolio",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Roger Richard Demello - Software Engineer, AI/ML",
    description: "Software engineer shipping machine learning and generative AI systems end to end. 3 production applications for 200+ users at 99.5% uptime.",
    site: "@rogerr_289",
    creator: "@rogerr_289",
    // twitter:image is generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`scroll-smooth ${serif.variable} ${inter.variable} ${mono.variable}`}
    >
      <body className="bg-background text-foreground font-sans antialiased">
        <a
          href="#main-content"
          className="sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:px-4 focus:py-2 focus:bg-primary focus:text-primary-foreground focus:rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-background focus:w-auto focus:h-auto focus:m-0 focus:overflow-visible focus:[clip:auto]"
        >
          Skip to content
        </a>
        {children}
      </body>
    </html>
  );
}
