import type { Metadata } from "next";
import { Instrument_Serif, Inter, JetBrains_Mono } from "next/font/google";
import "./globals.css";

// Editorial display serif for headings - elegant, distinctive, not a default sans.
const serif = Instrument_Serif({
  subsets: ["latin"],
  weight: "400",
  style: ["normal", "italic"],
  variable: "--font-display",
  display: "swap",
});

// Clean workhorse for body copy.
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

// Monospace for labels, metadata, terminal UI, and code.
const mono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
  display: "swap",
});

export const metadata: Metadata = {
  metadataBase: new URL("https://rogerdemello.tech"),
  title: "Roger Richard Demello - AI / ML Engineer & Data Scientist",
  description: "AI Engineer, Machine Learning Engineer, and Data Scientist. Building production-grade LLM applications and AI agents, training ML models, and turning data into insight - RAG pipelines, vector databases, agentic workflows, Python, FastAPI, LangChain, AWS.",
  keywords: [
    "Roger Demello",
    "AI Engineer",
    "Machine Learning Engineer",
    "Data Scientist",
    "LLM Applications",
    "AI Agents",
    "RAG Pipelines",
    "Vector Databases",
    "Agentic Workflows",
    "LangChain",
    "Deep Learning",
    "Data Science",
    "AWS Cloud",
    "Python",
    "FastAPI",
    "Portfolio"
  ],
  authors: [{ name: "Roger Richard Demello" }],
  creator: "Roger Richard Demello",
  openGraph: {
    type: "website",
    locale: "en_US",
    url: "https://rogerdemello.tech/",
    title: "Roger Richard Demello - AI / ML Engineer & Data Scientist",
    description: "AI Engineer, ML Engineer & Data Scientist. Production-grade LLM applications and AI agents, ML models, RAG pipelines, vector databases, FastAPI, LangChain.",
    siteName: "Roger Demello Portfolio",
    // og:image is generated by app/opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Roger Richard Demello - AI / ML Engineer & Data Scientist",
    description: "AI Engineer, ML Engineer & Data Scientist. Production-grade LLM applications and AI agents, ML models, RAG pipelines, vector databases, and data analytics.",
    // twitter:image is generated by app/twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`scroll-smooth ${serif.variable} ${inter.variable} ${mono.variable}`}
    >
      <body className="bg-background text-foreground font-sans antialiased">
        <a
          href="#main-content"
          className="sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[100] focus:px-4 focus:py-2 focus:bg-primary focus:text-primary-foreground focus:rounded-lg focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-background focus:w-auto focus:h-auto focus:m-0 focus:overflow-visible focus:[clip:auto]"
        >
          Skip to content
        </a>
        {children}
      </body>
    </html>
  );
}
